class EX002
{public static void main(String[] args)
	{
		String fac="FAS";
		int n=3;
		double p=10.5;
		int m=5;
		char w1='&';
		boolean isTH=true;
		
		System.out.println(fac);
		System.out.println(n);
		System.out.println(p);
		System.out.println(m);
		System.out.println(w1);
		System.out.println(isTH);
		
		System.out.println("MY FACULTY IS"+fac);
		System.out.println("THE RESULT 01 IS "+(n+m));
		System.out.println("THE RESULT 02 IS "+(p+m));
	}
	
	
}